### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by MemeSauce73** [KarstSkarn/ChAIScrapper#3]
1. The files needed to start it are entirely missing from the folder.  The files that are missing are ChAISData.xml and ChAIScrapper.exe

**Comment by KarstSkarn** [comment]
Hello there! Check out the latest release (Currently v2.1). It should address most if not all bugs you experienced.

By the way: the ChAISData.xml file is generated when you first execute the .exe file. This is done to ensure that you edit a clean and fresh configuration file. So just open the .exe and then close it afterwards and you'll see that it created that file.

I hope that helps you!
